version: "3"
services:
  api:
    image: fermetin/letbe-api
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50055:50055"
#    depends_on:
#      - db
