name: "Build, Test and Deploy to Dev Server"

on:
  push:
    branches:
      - dev

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{ job.environment.name }}
      # - name: Set ENV file
      #   env:
      #     ENV_FILE: ${{ secrets.DEV_ENV_FILE }}
      #   run: |
      #     echo "$ENV_FILE" > .env

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/bake-action@v2.3.0
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy docker-compose.yml to linode
        run: sshpass -v -p ${{ secrets.LINODE_PASSWORD }} scp -o StrictHostKeyChecking=no docker-compose.yml root@${{ vars.LINODE_IP }}:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.LINODE_IP }}
          username: root
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            cd ~
            docker-compose down
            docker-compose pull
            docker-compose up -d
