name: "Build, Test and Deploy to Dev Server"

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

          envkey_HOST: ${{secrets.HOST}}
          envkey_HOST_PORT: ${{secrets.HOST_PORT}}

          envkey_DB: ${{secrets.DB}}
          envkey_DB_PORT: ${{secrets.DB_PORT}}
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}

          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Build and test code
        run: |
          cargo build --verbose
          cargo test --verbose
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/bake-action@v2.3.0
        with:
          push: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
  deploy:
    needs: build
    environment: dev
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      LINODE_IP: ${{ secrets.LINODE_IP }}
      LINODE_PASSWORD: ${{ secrets.LINODE_PASSWORD }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy docker-compose.yml to linode
        run: sshpass -v -p $LINODE_PASSWORD scp -o StrictHostKeyChecking=no docker-compose.yml root@$LINODE_IP:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: $LINODE_IP
          username: root
          password: $LINODE_PASSWORD
          script: |
            cd ~
            docker-compose down
            docker-compose pull
            docker-compose up -d
